author: "Tobe O <thosakwe@gmail.com>"
description: "Generates Dart code to automatically check for a new version of the current package."
homepage: "https://github.com/thosakwe/check_for_update.git"
name: "check_for_update"
version: "1.0.1"
environment:
  sdk: ">=1.19.0"
dependencies: 
  build: "^0.7.0"
  code_builder: "^1.0.0-beta"
  pubspec: "^0.0.14"
  pub_semver: "^1.3.0"